# Generated by Django 5.2.1 on 2025-05-14 06:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_bankinginformation_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinginformation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, help_text='Date and time when the record was last updated', verbose_name='updated at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, help_text='Date and time when the record was last updated', verbose_name='updated at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, help_text='Date and time when the record was last updated', verbose_name='updated at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, help_text='Date and time when the record was last updated', verbose_name='updated at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplieraddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, help_text='Date and time when the record was last updated', verbose_name='updated at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierpartner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, help_text='Date and time when the record was last updated', verbose_name='updated at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, help_text='Date and time when the record was last updated', verbose_name='updated at'),
            preserve_default=False,
        ),
    ]
